[project]
name = "remote-docker-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beartype>=0.20.2",
    "flask>=3.1.0",
    "plotly>=6.0.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
